name: Generate Shift Slots (Daily)

on:
  schedule:
    - cron: '1 23 * * *'   # 00:01 CET
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install pandas openpyxl

      - name: Run generate_shiftslots.py
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          python generate_shiftslots.py \
            --template templates/shiftslots_template.xlsx \
            --outdir shiftslots \
            --range $(date -u +"%Y-%m-%d") $(date -u +"%Y-%m-%d")

      - name: Commit and push updates
        if: success()
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add shiftslots/*.xlsx || true
          git commit -m "Auto-update shiftslots ($(date))" || echo "No changes"
          git push
